(.venv) esc@asus:~/Músicas/experimentos_speedupy-paper$ ./run_exps_med.sh 
[FASE 3] Início: 2025-05-01 08:01:47
Collecting mmh3==4.0.1 (from -r speedupy/requirements.txt (line 1))
  Using cached mmh3-4.0.1-cp312-cp312-linux_x86_64.whl
Collecting numpy==1.26.4 (from -r speedupy/requirements.txt (line 2))
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting scipy==1.12.0 (from -r speedupy/requirements.txt (line 3))
  Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting xxhash==3.4.1 (from -r speedupy/requirements.txt (line 4))
  Using cached xxhash-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached scipy-1.12.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.8 MB)
Using cached xxhash-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
Installing collected packages: mmh3, xxhash, numpy, scipy
Successfully installed mmh3-4.0.1 numpy-1.26.4 scipy-1.12.0 xxhash-3.4.1
Collecting matplotlib
  Using cached matplotlib-3.10.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.57.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.5/102.5 kB 909.7 kB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Requirement already satisfied: numpy>=1.23 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib) (1.26.4)
Collecting packaging>=20.0 (from matplotlib)
  Downloading packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.2.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (8.9 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Collecting python-dateutil>=2.7 (from matplotlib)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached matplotlib-3.10.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
Downloading contourpy-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.7/323.7 kB 3.6 MB/s eta 0:00:00
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.57.0-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 4.2 MB/s eta 0:00:00
Using cached kiwisolver-1.4.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
Downloading packaging-25.0-py3-none-any.whl (66 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 4.7 MB/s eta 0:00:00
Downloading pillow-11.2.1-cp312-cp312-manylinux_2_28_x86_64.whl (4.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 6.3 MB/s eta 0:00:00
Using cached pyparsing-3.2.3-py3-none-any.whl (111 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pyparsing, pillow, packaging, kiwisolver, fonttools, cycler, contourpy, python-dateutil, matplotlib
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.57.0 kiwisolver-1.4.8 matplotlib-3.10.1 packaging-25.0 pillow-11.2.1 pyparsing-3.2.3 python-dateutil-2.9.0.post0 six-1.17.0
Generating particle spin-0.5 particle pairs
ETA:    0s [26813585 pairs generated]
26813585 particles in 'SrcLeft.npy.gz'
26813585 particles in 'SrcRight.npy.gz'
Detecting particles for Alice's arm
./run_before/epr_prepare.sh, linha 9:  4851 Morto                   python3.12 station_py39.py SrcLeft.npy.gz
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 421, in _send_bytes
    self._send(buf)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Detecting particles for Bob's arm
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
./run_before/epr_prepare.sh, linha 10:  4887 Morto                   python3.12 station_py39.py SrcRight.npy.gz
Process ForkPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 421, in _send_bytes
    self._send(buf)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from seaborn) (1.26.4)
Collecting pandas>=1.2 (from seaborn)
  Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas>=1.2->seaborn)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas>=1.2->seaborn)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, pandas, seaborn
Process ForkPoolWorker-5:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Successfully installed pandas-2.2.3 pytz-2025.2 seaborn-0.13.2 tzdata-2025.2
Collecting imageio
  Using cached imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: numpy in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from imageio) (1.26.4)
Requirement already satisfied: pillow>=8.3.2 in /home/esc/Músicas/.venv/lib/python3.12/site-packages (from imageio) (11.2.1)
Using cached imageio-2.37.0-py3-none-any.whl (315 kB)
Installing collected packages: imageio
Successfully installed imageio-2.37.0
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 1000
[MODE: intra_exec] Executando belief_propagation com entrada 1000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 5500
[MODE: intra_exec] Executando belief_propagation com entrada 5500...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 10000
[MODE: intra_exec] Executando belief_propagation com entrada 10000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 14500
[MODE: intra_exec] Executando belief_propagation com entrada 14500...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 19000
[MODE: intra_exec] Executando belief_propagation com entrada 19000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO belief_propagation APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 1e6
[MODE: intra_exec] Executando cvar com entrada 1e6...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 5e6
[MODE: intra_exec] Executando cvar com entrada 5e6...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 10e6
[MODE: intra_exec] Executando cvar com entrada 10e6...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 50e6
[MODE: intra_exec] Executando cvar com entrada 50e6...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 100e6
[MODE: intra_exec] Executando cvar com entrada 100e6...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO cvar APÓS intra_exec]
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO vince_sim APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 2000000
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando basic_spheres com entrada 2000000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 5000000
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando basic_spheres com entrada 5000000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 8000000
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando basic_spheres com entrada 8000000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 11000000
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando basic_spheres com entrada 11000000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 13000000
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando basic_spheres com entrada 13000000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO basic_spheres APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada -20
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando walking_colloid com entrada -20...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada -50
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando walking_colloid com entrada -50...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada -80
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando walking_colloid com entrada -80...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada -110
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando walking_colloid com entrada -110...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada -140
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exec] Executando walking_colloid com entrada -140...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO walking_colloid APÓS intra_exec]
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO epr_analyse APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 2000
[MODE: intra_exec] Executando fft com entrada 2000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 3500
[MODE: intra_exec] Executando fft com entrada 3500...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 5000
[MODE: intra_exec] Executando fft com entrada 5000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 6500
[MODE: intra_exec] Executando fft com entrada 6500...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 8000
[MODE: intra_exec] Executando fft com entrada 8000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO fft APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 5000
[MODE: intra_exec] Executando gauss_legendre_quadrature com entrada 5000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 7000
[MODE: intra_exec] Executando gauss_legendre_quadrature com entrada 7000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 9000
[MODE: intra_exec] Executando gauss_legendre_quadrature com entrada 9000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 11000
[MODE: intra_exec] Executando gauss_legendre_quadrature com entrada 11000...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 13000
[MODE: intra_exec] Executando gauss_legendre_quadrature com entrada 13000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO gauss_legendre_quadrature APÓS intra_exec]
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO heat_distribution_lu APÓS intra_exec]
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 45
[MODE: intra_exec] Executando look_and_say com entrada 45...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 46
[MODE: intra_exec] Executando look_and_say com entrada 46...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 47
[MODE: intra_exec] Executando look_and_say com entrada 47...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 48
[MODE: intra_exec] Executando look_and_say com entrada 48...
[MODE: intra_exec] Limpando cache e executando setup.py para entrada 49
[MODE: intra_exec] Executando look_and_say com entrada 49...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO look_and_say APÓS intra_exec]
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO TINY_GSHCGP APÓS intra_exec]
[MODE: intra_exp] Setup único para belief_propagation
[MODE: intra_exp] Executando belief_propagation com entrada 1000...
[MODE: intra_exp] Executando belief_propagation com entrada 5500...
[MODE: intra_exp] Executando belief_propagation com entrada 10000...
[MODE: intra_exp] Executando belief_propagation com entrada 14500...
[MODE: intra_exp] Executando belief_propagation com entrada 19000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO belief_propagation APÓS intra_exp]
[MODE: intra_exp] Setup único para cvar
[MODE: intra_exp] Executando cvar com entrada 1e6...
[MODE: intra_exp] Executando cvar com entrada 5e6...
[MODE: intra_exp] Executando cvar com entrada 10e6...
[MODE: intra_exp] Executando cvar com entrada 50e6...
[MODE: intra_exp] Executando cvar com entrada 100e6...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO cvar APÓS intra_exp]
[MODE: intra_exp] Setup único para vince_sim
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO vince_sim APÓS intra_exp]
[MODE: intra_exp] Setup único para basic_spheres
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exp] Executando basic_spheres com entrada 2000000...
[MODE: intra_exp] Executando basic_spheres com entrada 5000000...
[MODE: intra_exp] Executando basic_spheres com entrada 8000000...
[MODE: intra_exp] Executando basic_spheres com entrada 11000000...
[MODE: intra_exp] Executando basic_spheres com entrada 13000000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO basic_spheres APÓS intra_exp]
[MODE: intra_exp] Setup único para walking_colloid
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
<unknown>:16: SyntaxWarning: invalid escape sequence '\s'
Traceback (most recent call last):
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 28, in <module>
    setup_experiment(sys.argv[1])
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/setup.py", line 20, in setup_experiment
    overwrite_decorated_experiment(experiment)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/experiment_service.py", line 85, in overwrite_decorated_experiment
    overwrite_decorated_script(script)
  File "/home/esc/Músicas/experimentos_speedupy-paper/speedupy/setup_exp/services/script_service.py", line 79, in overwrite_decorated_script
    with open(script.name, 'wt') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dnacc/derjaguin.py'
[MODE: intra_exp] Executando walking_colloid com entrada -20...
[MODE: intra_exp] Executando walking_colloid com entrada -50...
[MODE: intra_exp] Executando walking_colloid com entrada -80...
[MODE: intra_exp] Executando walking_colloid com entrada -110...
[MODE: intra_exp] Executando walking_colloid com entrada -140...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO walking_colloid APÓS intra_exp]
[MODE: intra_exp] Setup único para epr_analyse
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO epr_analyse APÓS intra_exp]
[MODE: intra_exp] Setup único para fft
[MODE: intra_exp] Executando fft com entrada 2000...
[MODE: intra_exp] Executando fft com entrada 3500...
[MODE: intra_exp] Executando fft com entrada 5000...
[MODE: intra_exp] Executando fft com entrada 6500...
[MODE: intra_exp] Executando fft com entrada 8000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO fft APÓS intra_exp]
[MODE: intra_exp] Setup único para gauss_legendre_quadrature
[MODE: intra_exp] Executando gauss_legendre_quadrature com entrada 5000...
[MODE: intra_exp] Executando gauss_legendre_quadrature com entrada 7000...
[MODE: intra_exp] Executando gauss_legendre_quadrature com entrada 9000...
[MODE: intra_exp] Executando gauss_legendre_quadrature com entrada 11000...
[MODE: intra_exp] Executando gauss_legendre_quadrature com entrada 13000...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO gauss_legendre_quadrature APÓS intra_exp]
[MODE: intra_exp] Setup único para heat_distribution_lu
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO heat_distribution_lu APÓS intra_exp]
[MODE: intra_exp] Setup único para look_and_say
[MODE: intra_exp] Executando look_and_say com entrada 45...
[MODE: intra_exp] Executando look_and_say com entrada 46...
[MODE: intra_exp] Executando look_and_say com entrada 47...
[MODE: intra_exp] Executando look_and_say com entrada 48...
[MODE: intra_exp] Executando look_and_say com entrada 49...
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO look_and_say APÓS intra_exp]
[MODE: intra_exp] Setup único para TINY_GSHCGP
[LIMPANDO CACHE E PASTA SPEEDUPY DO EXPERIMENTO TINY_GSHCGP APÓS intra_exp]
[FASE 3] Fim: 2025-05-01 08:24:25 — Duração: 1358s
(.venv) esc@asus:~/Músicas/experimentos_speedupy-paper$ 
